# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74cd674cb79471dd64964f781c0a958a1f5a815cd9cd5bb415e3815e048005f83dcdd6fb30c29a78c9d20ede21024f54d64d5e2ad13ecd8f53382c0d034f44db

test:
  secret_key_base: 7b8c4dbdb6d620314da515d9382b7163f3bf9ec400451351fad20026622c38adfd7950f4366c02e0157594a3b2465fcd1d6a790839cf9d3400422e47eadbd79a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
